remote_theme: pages-themes/cayman@v0.2.0
title: Music Genre Prediction
author: Ruwei Ma, Annette Gisella, Richard Hoepfinger, Tuan Ha, Arthur Odom
usemathjax: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
